---
name: MSDOS-Attrib
version: 1.02
author:
  - Christopher J. Madsen <cjm@pobox.com>
abstract: Get or set MS-DOS file attributes
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Test::More: 0
recommends:
  XSLoader: 0
dynamic_config: 0
provides:
  MSDOS::Attrib:
    file: lib/MSDOS/Attrib.pm
    version: 1.02
generated_by: Module::Build version 0.28
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
